# 1. From the following tables, write a  SQL query to find all the orders issued by the salesman 
# 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
SELECT * FROM ORDERS
WHERE SALESMAN_ID = (
	SELECT SALESMAN_ID 
    FROM SALESMAN
	WHERE NAME = 'Paul Adam');

# 2. From the following tables write a  SQL query to find all orders generated by 
# London-based salespeople. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
SELECT * FROM ORDERS
WHERE SALESMAN_ID = 
	(SELECT SALESMAN_ID
    FROM SALESMAN
    WHERE CITY = 'London');
    
# 3. From the following tables write a  SQL query to find all orders generated by the 
# salespeople who may work for customers whose id is 3007. Return ord_no, purch_amt, 
# ord_date, customer_id, salesman_id.
SELECT * FROM ORDERS
WHERE SALESMAN_ID = 
	(SELECT DISTINCT SALESMAN_ID
    FROM ORDERS
    WHERE CUSTOMER_ID = 3007);
    
# 4. From the following tables write a  SQL query to find the order values greater than 
# the average order value of 10th October 2012. Return ord_no, purch_amt, ord_date, 
# customer_id, salesman_id.
SELECT * FROM ORDERS
WHERE PURCH_AMT > 
	(SELECT AVG(PURCH_AMT) FROM ORDERS
    WHERE ORD_DATE = '2012-10-10');
    
# 5. From the following tables, write a SQL query to find all the orders generated in New York city. 
# Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
SELECT * FROM ORDERS
WHERE SALESMAN_ID IN
	(SELECT SALESMAN_ID FROM SALESMAN
    WHERE CITY = 'New York');

# 6. From the following tables write a  SQL query to determine the commission of 
# the salespeople in Paris. Return commission.
SELECT COMMISSION FROM SALESMAN
WHERE SALESMAN_ID in
	(SELECT SALESMAN_ID FROM CUSTOMER
    WHERE CITY = 'Paris');
    
# 7. Write a query to display all the customers whose ID is 2001 below the salesperson ID of Mc 
# Lyon.
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID =
    (SELECT SALESMAN_ID - 2001
     FROM SALESMAN
     WHERE NAME = 'Mc Lyon');
     
# 8. From the following tables write a  SQL query to count the number of customers with grades 
# above the average in New York City. Return grade and count.  
SELECT GRADE, COUNT(CITY) FROM CUSTOMER
GROUP BY GRADE
HAVING GRADE > 
	(SELECT AVG(GRADE) FROM CUSTOMER
    WHERE CITY = 'New York');
    
# 9. From the following tables, write a  SQL query to find those salespeople who earned the
# maximum commission. Return ord_no, purch_amt, ord_date, and salesman_id.
SELECT * FROM ORDERS 
WHERE SALESMAN_ID IN
	(SELECT SALESMAN_ID FROM SALESMAN
    WHERE COMMISSION = 
		(SELECT MAX(COMMISSION) FROM SALESMAN));
        
# 10. From the following tables write  SQL query to find the customers who placed orders on 
# 17th August 2012. Return ord_no, purch_amt, ord_date, customer_id, salesman_id and cust_name.
-- Selecting all columns from the 'orders' table and the 'cust_name' column from the 'customer' table
SELECT O.*, C.CUST_NAME
FROM ORDERS O, CUSTOMER C
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID
AND O.ORD_DATE = '2012-08-17';

